### ISSUE TITLE
Login required after every refresh of page.

### ISSUE THREAD

**Issue by codea-holic** [codea-holic/Reels#1]
**After every refresh, I need to log in again and again.  Is there any method to maintain the data of the signed user?**

- [x]  On the login page, I want to restore the user data, if any user signed in already.

**Comment by Debraj-Kundu** [comment]
You can use **React.useEffect()** hook to implement this feature..

**Comment by codea-holic** [comment]
### Could you help me, with the code?

**Comment by webtdeveloper** [comment]
**Please Review my change and pull it, If you found an issue, Suggest me...**
